### ISSUE TITLE
代码是论文Image-to-Markup Generation with Coarse-to-Fine Attention的复现么

### ISSUE THREAD

**Issue by kim-yhow** [LinXueyuanStdio/LaTeX_OCR#10]
您好，首先很感谢您开源了这个代码，我跑了这个代码发现EM指标只有51%，没有达到论文中的76%，这份代码是不是与[论文](http://lstm.seas.harvard.edu/latex/)的里提到的方法不一样。因为我没有看到代码中有论文中提到的row encoder 方法

**Comment by LinXueyuanStdio** [comment]
您好。是的。这个项目的目的是学习。Image-to-Markup的论文由于能力所限，并没有完全复现，所以EM很低。您说的row encoder是其中一个缺点。

**Comment by kim-yhow** [comment]
好的，谢谢您
