### ISSUE TITLE
small准确率

### ISSUE THREAD

**Issue by PKU-FengShuo** [LinXueyuanStdio/LaTeX_OCR#15]
跑了一下small的数据，准确率很低，请问这是正常现象还是有问题呢？

25/25 [==============================] - 3s - loss: 318.912090 - perplexity: inf - lr: 0.100000     
- Training:  - 3s - loss: 318.912090 - perplexity: inf - lr: 0.100000
- Evaluating...
writting file  results/small/formulas_val/ref.txt
writting file  results/small/formulas_val/hyp_0.txt
writting file  results/small/formulas_val/hyp_1.txt
Loaded 30 formulas from results/small/formulas_val/ref.txt
Loaded 30 formulas from results/small/formulas_val/hyp_0.txt
- Eval:  BLEU-4 is 0.00  ||  ExactMatchScore is 0.00  ||  perplexity is -212269996680525689170079392416506714400026115682911821216976265628196223383119470307957417682148579524265885659877825415860269457788221744218112.00  ||  EditDistance is 7.41 
- Elapsed time: 9.26, learning rate: 0.10000

**Comment by LinXueyuanStdio** [comment]
small数据集只是确保程序能跑，需要准确率只能用完整数据集，或者大一点的数据集。再说small数据集不到100条公式，模型学什么?
