### ISSUE TITLE
关于方程组

### ISSUE THREAD

**Issue by ccl-private** [LinXueyuanStdio/LaTeX_OCR#23]
我在test.norm.txt第一行加入了一个方程组的latex
\begin{cases}& \text{ if } x=5 \\ & \text{ if } x=6 \end{cases}
但生成的图片不太对，
![image](https://user-images.githubusercontent.com/36214675/118442024-9adbde80-b71c-11eb-8153-e8773ca83a2d.png)

期望生成这样的
![image](https://user-images.githubusercontent.com/36214675/118442119-bf37bb00-b71c-11eb-8cee-00e69e4f049a.png)
要怎么处理呢

**Comment by ccl-private** [comment]
我注意到你的数据集里本来就要方程组，生成的图片全错了，比如测试集里的1078.png

**Comment by LinXueyuanStdio** [comment]
```
\begin{cases}& \text{ if } x=5 \ & \text{ if } x=6 \end{cases}
```
写错了，应该是
```
\begin{cases}& \text{ if } x=5 \\ & \text{ if } x=6 \end{cases}
```
才能生成下面的。
语法不对的latex，生成的当然也不对

其次，图片是标准的latex渲染引擎自动渲染的，人为无关。

**Comment by ccl-private** [comment]
用
\begin{cases}& \text{ if } x=5 \\ & \text{ if } x=6 \end{cases}
生成的也不对，还是老样子，是不是用的latex渲染引擎有问题哈

**Comment by ccl-private** [comment]
data/train.formulas.norm.txt里第489行也有大括号，\operatorname* { l i m } _ { q \to 1 } { \frac { 1 } { 2 } } \Big [ Z ^ { a | a } ( L ; q ) - Z ^ { a } ( L ; q ) \Big ] = \left\{ \begin{cases} { \frac { 1 } { 2 } \left( 2 ^ { L - 1 } - 2 ^ { \lfloor \frac { L } { 2 } \rfloor } \right) , } & { a = 1 o r + } \\ { \frac { 1 } { 2 } \left( 2 ^ { L } - 2 ^ { \lfloor \frac { L + 1 } { 2 } \rfloor } \right) ule { 0 in } { 0.25 in } , } & { a = 2 o r F } \\ \end{cases} \right.

生成的公式图也是错的

**Comment by ccl-private** [comment]
找到原因了，latex转tex文件不对
![Screenshot from 2021-06-24 14-04-11](https://user-images.githubusercontent.com/36214675/123210831-26ebdd80-d4f5-11eb-89e9-6656681922ac.png)
改一下这里就好

**Comment by LinXueyuanStdio** [comment]
啊这，很奇怪啊
可能是LaTeX版本的问题吧
why it works?...

**Comment by ccl-private** [comment]
![Screenshot from 2021-06-24 17-15-37](https://user-images.githubusercontent.com/36214675/123238512-1e090500-d511-11eb-8b48-60e2c081c138.png)
这是我的pdflatex版本
