### ISSUE TITLE
关于测试集的问题

### ISSUE THREAD

**Issue by NicholasIrving** [LinXueyuanStdio/LaTeX_OCR#4]
我是CV的初学者，想通过你的这个项目有一些对识别的了解。通过阅读你的代码我发现在生成测试集的时候，用了和训练数据时候一样的DataGenerator，同时用了formula和image两个指标，按道理不是应该要么知道formula得到image，要么知道image得到formula的吗？同时知道的话不是应该是训练集吗？

**Comment by CaiHandsome** [comment]
我也有这个疑问，请问您弄清楚了吗

**Comment by CaiHandsome** [comment]
您好，我也遇到这个问题。
但是我试验了一下发现DataGenerator刚开始只负责读取文件夹，images文件夹下没有照片也不会报错

**Comment by LinXueyuanStdio** [comment]
tf是静态图，网络训练部分和测试部分同时生成，不然训练图和测试图会不一样。实际上在测试时formula只用于和预测结果计算分数，不参与识别。
