### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by NicholasIrving** [LinXueyuanStdio/LaTeX_OCR#6]
训练的时候出现了
![image](https://user-images.githubusercontent.com/22784080/63419030-a52d5380-c436-11e9-844f-4e3ed05ba573.png)
显存占用特别的大，是为什么呢？
而且训练速度很慢，用的是泰坦5，GPU占用率只有20+，请问是正常现象还是出了什么问题了呢？

**Comment by LinXueyuanStdio** [comment]
训练慢正常。
如果是因为内存问题，可以手动编辑`xxx.matching.txt`文件或者更改配置文件，以决定多少公式用于训练。

**Comment by Junwei9103** [comment]
你好，我按照你的步骤，配置了环境，生成数据后开始训练，为什么我的GPU利用率为0啊，是哪里的参数要设置吗？Linux系统

**Comment by LinXueyuanStdio** [comment]
@Junwei9103 用的是gpu版的tf吗？

**Comment by Junwei9103** [comment]
装的tf版本不对，已经解决了问题，现在已经在训练了，非常感谢！
