### ISSUE TITLE
环境配置问题

### ISSUE THREAD

**Issue by Jeremy-lf** [LinXueyuanStdio/LaTeX_OCR#8]
MagickCore/magick.c:100:12: fatal error: 'libxml/parser.h' file not found

**Comment by LinXueyuanStdio** [comment]
这是 Magick 的问题，与本项目无关

另外，magick 是用来生成图片的，如果你不想自己构建数据集，可以移步这个 repo 下载数据：

https://github.com/LinXueyuanStdio/Data-for-LaTeX_OCR
